input {
  beats {
    port => 5044
  }
}

filter {
  if [log_type] == "nginx_access" {
    json {
      source => "message"
      target => "nginx"
      skip_on_invalid_json => true
    }

    date {
      match => [ "[nginx][time]", "ISO8601" ]
      target => "@timestamp"
    }

    mutate {
      convert => {
        "[nginx][status]" => "integer"
        "[nginx][body_bytes_sent]" => "integer"
        "[nginx][request_time]" => "float"
        "[nginx][upstream_response_time]" => "float"
      }
      add_field => {
        "[service][name]" => "nginx"
        "[event][dataset]" => "nginx.access"
      }
    }
  } else if [log_type] == "nginx_error" {
    mutate {
      add_field => {
        "[service][name]" => "nginx"
        "[event][dataset]" => "nginx.error"
      }
    }
  } else if [log_type] == "apollo_json" {
    json {
      source => "message"
      target => "apollo"
      skip_on_invalid_json => true
    }

    date {
      match => [ "[apollo][time]", "UNIX_MS" ]
      target => "@timestamp"
    }

    mutate {
      add_field => {
        "[service][name]" => "apollo-server"
        "[event][dataset]" => "apollo.application"
      }
    }
  }
}

output {
  if [event][dataset] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "%{[event][dataset]}-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "lab-logs-%{+YYYY.MM.dd}"
    }
  }

  stdout {
    codec => rubydebug
  }
}

